#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Feature: Add ASC/DESC Sort Direction for Reports

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="/Users/bobrietveld/Documents/Techleap/sodt_app"

# Check if we're in the right directory
if [ ! -f "$PROJECT_ROOT/package.json" ]; then
    echo -e "${RED}Error: Cannot find package.json in $PROJECT_ROOT${NC}"
    exit 1
fi

cd "$PROJECT_ROOT"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
npm install

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting development server..."

# Start Next.js development server in background
npm run dev &
NEXTJS_PID=$!

# Wait for Next.js to start
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo "  Reports Page: http://localhost:3000/reports"
echo ""
echo "Development Commands:"
echo "  npm run dev          - Start development server"
echo "  npm run build        - Build for production"
echo "  npm run lint         - Run ESLint"
echo "  npx convex dev       - Start Convex dev server"
echo ""
echo "Process IDs:"
echo "  Next.js PID: $NEXTJS_PID"
echo ""
echo "To stop: kill $NEXTJS_PID"
echo ""
